services:
  storefront:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY:-}
        NUXT_PUBLIC_STRIPE_PUBLIC_KEY: ${NUXT_PUBLIC_STRIPE_PUBLIC_KEY:-}
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
